// Generated by CoffeeScript 1.9.2
var bdd, expector, injector, tdd;

module.exports.bdd = bdd = require('./bdd');

module.exports.tdd = tdd = require('./tdd');

module.exports.injector = injector = require('./injector');

module.exports.expector = expector = require('./expector');

module.exports.$$beforeEach = function(config, callback) {
  var e;
  try {
    tdd.$$beforeEach(config);
    bdd.$$beforeEach(config);
    injector.$$beforeEach(config);
    expector.$$beforeEach(config);
    return callback();
  } catch (_error) {
    e = _error;
    return callback(e);
  }
};
