// Generated by CoffeeScript 1.9.2
module.exports = {
  init: function(arg, callback) {
    var pipe, prompt;
    pipe = arg.pipe, prompt = arg.prompt;
    pipe.on('recurse.start', function(arg1, next) {
      var path;
      path = arg1.path;
      return next();
    });
    pipe.on('recurse.entering', function(arg1, next) {
      var path;
      path = arg1.path;
      return next();
    });
    pipe.on('recurse.found', function(arg1, next) {
      var path;
      path = arg1.path;
      return next();
    });
    pipe.on('recurse.end', function(data, next) {
      return next();
    });
    pipe.on('recurse.error', function(error, next) {
      return next();
    });
    return callback();
  }
};
