// Generated by CoffeeScript 1.9.2
var dev, fs, normalize, shared;

normalize = require('path').normalize;

fs = require('fs');

shared = require('./shared');

require('./tester');

module.exports = dev = shared.dev = {
  testDir: 'test',
  sourceDir: 'lib',
  compileTo: void 0,
  init: function(callback) {
    var pipe;
    pipe = objective.pipe;
    pipe.on('prompt.commands.register.ask', function(command, next) {
      command.create('dev.createModule', {
        description: 'Create new module in the current project.',
        run: require('./commands/create_module'),
        help: "\nUsage: dev.createModule " + dev.testDir + "/path/to/module_name [templateName]\n\nCreates the '" + dev.testDir + "' file and the corresponding '" + dev.sourceDir + "' file.\n\n    ie.\n\n        " + dev.testDir + "/path/to/module_name.js\n        " + dev.sourceDir + "/path/to/module_name.js\n\nThe paths match up so that when the '" + dev.sourceDir + "' file changes the\ncorresponding '" + dev.testDir + "' file can be found and run.\n\nIt is recommended to use underscores between the name parts\nso that the module injector can be used in tests.\n\n    ie.  \n\n        module_name.js will be injectable as ModuleName\n        (provided that it is unique project-wide)\n\nIf templateName is specified the corresponding template will be used.\n\n    ie.\n\n        ~/.objective/templates/dev/templateName_spec.js\n\n\nNOTE: The templates are only installed upon registration. (--register)\n",
        autoComplete: function(args, callback) {
          var directory, file, i, len, matches;
          if (args.length > 2) {
            return callback(null, null);
          }
          if (args.length === 1) {
            return callback(null, {
              type: 'path',
              startIn: normalize(dev.testDir + '/'),
              onlyDirectories: true
            });
          }
          if (args.length === 2) {
            try {
              directory = fs.readdirSync(process.env.HOME + '/.objective/templates/dev');
              matches = [];
              for (i = 0, len = directory.length; i < len; i++) {
                file = directory[i];
                if (file.match(new RegExp("_spec." + shared.language))) {
                  matches.push(file.replace("_spec." + shared.language, ''));
                }
              }
              return callback(null, matches);
            } catch (_error) {
              return callback(null, null);
            }
          }
        }
      });
      return next();
    });
    pipe.on('files.recurse.start', function(arg, next) {
      var path;
      path = arg.path;
      return next();
    });
    pipe.on('files.recurse.entering', function(arg, next) {
      var path;
      path = arg.path;
      return next();
    });
    pipe.on('files.recurse.found', function(arg, next) {
      var path;
      path = arg.path;
      return next();
    });
    pipe.on('files.recurse.end', function(data, next) {
      return next();
    });
    pipe.on('files.recurse.error', function(error, next) {
      return next();
    });
    return callback();
  }
};
