// Generated by CoffeeScript 1.9.2
global.context = function(descr, callback) {
  console.log("context '" + descr + "' not implemented");
  if (callback != null) {
    return callback();
  }
};

global.it = function(descr, callback) {
  console.log("it '" + descr + "' not implemented");
  if (callback != null) {
    return callback();
  }
};
