// Generated by CoffeeScript 1.9.2
global.before = function(fn) {};

global.beforeEach = function(fn) {};

global.afterEach = function(fn) {};

global.afterAll = function(fn) {};

global.context = function(descr, fn) {
  console.log({
    caller: caller()
  });
  console.log("context '" + descr + "' not implemented");
  if (fn != null) {
    fn();
  }
  return 'moo';
};

global.describe = global.context;

global.it = function(descr, fn) {
  console.log("it '" + descr + "' not implemented");
  if (fn != null) {
    return fn();
  }
};
