// Generated by CoffeeScript 1.9.2
var TODO, debug, error, info, logger, pipe;

logger = objective.logger, pipe = objective.pipe;

info = logger.info, error = logger.error, debug = logger.debug, TODO = logger.TODO;

TODO('inject into pipe args');

TODO('test timeouts error');

module.exports = function() {
  debug('using default test reporter');
  pipe.on('dev.test.before.all', function(payload, next) {
    console.log();
    return next();
  });
  pipe.on('dev.test.after.all', function(payload, next) {
    console.log();
    return next();
  });
  return pipe.on('dev.test.after.each', function(arg, next) {
    var test, testName;
    test = arg.test;
    if (test.type === 'test') {
      testName = test.node.path.slice(1).join(' - ');
      if (test.error == null) {
        console.log('PASSED - ' + testName);
        return next();
      }
      console.log('FAILED - ' + testName);
      console.log(test.error.stack);
      return next();
    }
    if (test.error != null) {
      testName = test.node.path.slice(1).join(' - ');
      console.log("ERROR - in '" + test.type + "' for '" + testName + "'");
      console.log("FN - " + (test.fn.toString()));
      console.log("STACK - " + test.error.stack);
    }
    return next();
  });
};
