// Generated by CoffeeScript 1.9.2
var EOL, blessed, columnnumber, content, currentLine, currentTest, enabled, fails, filename, fs, linenumber, nextLines, nextTest, origPrepareStackTrace, pad, pipe, previousLine, previousTest, render, screen, stack, stackReport, stepPosition, successCount, testPosition, text;

enabled = false;

origPrepareStackTrace = void 0;

module.exports.enable = function() {
  var dev;
  dev = require('../');
  enabled = true;
  origPrepareStackTrace = Error.prepareStackTrace;
  return Error.prepareStackTrace = function(_, stack) {
    return stack;
  };
};

module.exports.disable = function() {
  return Error.prepareStackTrace = origPrepareStackTrace;
};

blessed = require('blessed');

require('colors');

screen = void 0;

content = '';

text = void 0;

fails = void 0;

testPosition = 0;

stepPosition = 0;

pad = require('pad');

fs = require('fs');

EOL = require('os').EOL;

stack = [];

successCount = 0;

filename = void 0;

linenumber = void 0;

columnnumber = void 0;

currentTest = function() {
  var fail, num, path, pathLength;
  num = fails.length - 1 - testPosition;
  fail = fails[fails.length - 1 - testPosition];
  path = fail.node.path;
  pathLength = path.length;
  return ("" + (pad(2, (num + 1).toString(), '0'))).bold + " FAILED ".red.bold + path.join(' + ').bold;
};

previousTest = function() {
  var fail, num, path;
  num = fails.length - 2 - testPosition;
  fail = fails[fails.length - 2 - testPosition];
  if (fail == null) {
    return '';
  }
  path = fail.node.path;
  return (("" + (pad(2, (num + 1).toString(), '0'))).bold + " FAILED " + path.join(' + ')).grey;
};

nextTest = function() {
  var fail, num, path;
  num = fails.length - testPosition;
  fail = fails[fails.length - testPosition];
  if (fail == null) {
    return '';
  }
  path = fail.node.path;
  return (("" + (pad(2, (num + 1).toString(), '0'))).bold + " FAILED " + path.join(' + ')).grey;
};

currentLine = function() {
  var data, file, i, j, lines, num, ref, result;
  num = stepPosition;
  data = stack[num];
  filename = data.getFileName();
  linenumber = parseInt(data.getLineNumber());
  columnnumber = parseInt(data.getColumnNumber());
  if ((filename != null) && (linenumber != null)) {
    try {
      result = EOL;
      file = fs.readFileSync(filename);
      lines = file.toString().split(EOL);
      for (i = j = 0, ref = lines.length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        if (!(i + 7 > linenumber)) {
          continue;
        }
        if (!(i - 7 < linenumber)) {
          continue;
        }
        if (linenumber !== i + 1) {
          result += lines[i].grey + EOL;
        }
        if (linenumber === i + 1) {
          result += lines[i].bold + EOL;
        }
      }
    } catch (_error) {}
  }
  return (pad(2, (num + 1).toString(), '0').bold) + " - " + (data.toString()) + "\n" + result;
};

previousLine = function() {
  var data, num;
  num = stepPosition - 1;
  data = stack[num] || '';
  return ("" + (pad(2, (num + 1).toString(), '0'))).bold + " - " + data.toString().grey;
};

nextLines = function() {
  var data, i, j, lines, num, remaining;
  lines = "";
  for (i = j = 1; j <= 5; i = ++j) {
    num = stepPosition + i;
    data = stack[num];
    if (data == null) {
      continue;
    }
    lines += ("" + (pad(2, (num + 1).toString(), '0'))).bold + " - " + data.toString().grey + '\n';
  }
  remaining = stack.length - num - 1;
  if (remaining > 0) {
    lines += ("\n + " + (stack.length - num - 1) + " more").bold;
  }
  return lines;
};

stackReport = function() {
  return (currentLine()) + "\n\n" + (nextLines());
};

render = function() {
  var afterCount, beforeCount, count, fail, failsText, heading1, heading2, heading3;
  if (screen == null) {
    return;
  }
  count = fails.length;
  if (count === 0) {
    successCount++;
    content += successCount.toString();
    text.setContent(content);
    screen.render();
    return;
  }
  successCount = 0;
  content += '|';
  beforeCount = count - testPosition - 1;
  afterCount = testPosition;
  fail = fails[fails.length - 1 - testPosition];
  try {
    stack = fail.error.stack;
  } catch (_error) {}
  stack || (stack = []);
  heading1 = ("failed tests (" + count + ")").bold + "  up,down";
  try {
    heading2 = fail.error.toString().red.bold;
  } catch (_error) {}
  heading2 || (heading2 = "");
  heading3 = ("error stack (depth " + stack.length + ")") + "  left,right";
  failsText = "\n" + heading1 + "\n\n" + (previousTest()) + "\n" + (currentTest()) + "\n" + (nextTest()) + "\n\n" + heading2 + "\n" + heading3 + "\n\n" + (stackReport()) + "\n";
  text.setContent(failsText);
  return screen.render();
};

pipe = objective.pipe;

pipe.on('prompt.commands.register.ask', function(command) {
  var bell, close;
  close = void 0;
  bell = function() {};
  return command.create('stacks', {
    description: '(dev) Test failure error stack navigator.',
    keyStrokes: function(ch, key) {
      try {
        if (key.ctrl && (key.name === 'c' || key.name === 'd')) {
          module.exports.disable();
          blessed.program().clear();
          close();
        }
      } catch (_error) {}
      try {
        if (!(fails.length > 0)) {
          return;
        }
      } catch (_error) {
        return;
      }
      if (!fails.length) {
        return;
      }
      try {
        if (key.name === 'return') {
          objective.user.goto({
            type: 'dev.source.file',
            filename: filename,
            line: linenumber,
            column: columnnumber
          });
        }
      } catch (_error) {}
      try {
        if (key.name === 'up') {
          testPosition++;
          if (testPosition > fails.length - 1) {
            testPosition = fails.length - 1;
            bell();
            return;
          }
          render();
        }
      } catch (_error) {}
      try {
        if (key.name === 'down') {
          testPosition--;
          if (testPosition < 0) {
            testPosition = 0;
            bell();
            return;
          }
          render();
        }
      } catch (_error) {}
      try {
        if (key.name === 'left') {
          stepPosition--;
          if (stepPosition < 0) {
            stepPosition = 0;
            bell();
            return;
          }
          render();
        }
      } catch (_error) {}
      try {
        if (key.name === 'right') {
          stepPosition++;
          if (stepPosition > stack.length - 1) {
            stepPosition = stack.length - 1;
            bell();
            return;
          }
          return render();
        }
      } catch (_error) {}
    },
    run: function(args, callback) {
      module.exports.enable();
      objective.plugins.dev.reporters["default"].disable();
      close = callback;
      if (screen == null) {
        screen = blessed.screen({
          autoPadding: true,
          smartCSR: true
        });
      }
      if (text == null) {
        text = blessed.text({
          top: 'top',
          left: 'left',
          content: "Waiting for test."
        });
        screen.append(text);
      }
      blessed.program().clear();
      return process.nextTick(function() {
        text.setContent("Waiting for test.");
        return screen.render();
      });
    },
    help: "\nAfter each test run a new batch of failures will appear.\n\nUse 'up' and 'down' arrows to navigate previous and next failure.\n\nUse 'left' and 'right' to step into the stack of the current failure.\n"
  });
});

pipe.on('dev.test.before.all', function() {
  if (!enabled) {
    return;
  }
  fails = [];
  try {
    text.setContent(content);
    return screen.render();
  } catch (_error) {}
});

pipe.on('dev.test.after.each', function(arg) {
  var colour, test;
  test = arg.test;
  if (!enabled) {
    return;
  }
  content || (content = '');
  colour = test.error != null ? 'red' : 'green';
  if (test.type === 'test') {
    content += "T"[colour];
  } else if (test.type.match(/beforeAll/)) {
    content += "B"[colour];
  } else if (test.type.match(/beforeEach/)) {
    content += "b"[colour];
  } else if (test.type.match(/afterAll/)) {
    content += "A"[colour];
  } else if (test.type.match(/afterEach/)) {
    content += "a"[colour];
  }
  try {
    text.setContent(content);
    return screen.render();
  } catch (_error) {}
});

pipe.on('dev.test.after.all', function(arg) {
  var fn, functions;
  functions = arg.functions;
  if (!enabled) {
    return;
  }
  fails = (function() {
    var j, len, results;
    results = [];
    for (j = 0, len = functions.length; j < len; j++) {
      fn = functions[j];
      if (fn.error == null) {
        continue;
      }
      results.push(fn);
    }
    return results;
  })();
  testPosition = 0;
  stepPosition = 0;
  return render();
});
