// Generated by CoffeeScript 1.9.2
var CreateModule, fs, path, shared, uuid;

shared = require('../shared');

uuid = require('uuid');

fs = require('fs');

path = require('path');

module.exports = CreateModule = function(args, callback) {
  var ext, lang, newObjective, parts, stat, testDir, tpath;
  tpath = args[0];
  lang = shared.language;
  testDir = shared.dev.testDir;
  ext = tpath.split('.').pop();
  if (ext === lang) {
    'allgood';
  } else if (ext === 'coffee' || ext === 'js') {
    lang = ext;
  } else {
    tpath += '.' + lang;
  }
  parts = tpath.split('.');
  ext = parts.pop();
  tpath = parts.join('.') + '_' + testDir + '.' + ext;
  try {
    stat = fs.lstatSync(tpath);
    if (stat.isDirectory()) {
      return callback(new Error('Cannot create module at ' + tpath));
    }
    return callback(new Error('File already exists at ' + tpath));
  } catch (_error) {}
  console.log('TODO: online creation');
  newObjective = {
    uuid: uuid.v4(),
    title: 'TTTT',
    description: '',
    "private": shared.objective["private"]
  };
  return CreateModule.writeSpecFile(newObjective, function(e) {
    if (e != null) {
      return callback(e);
    }
    CreateModule.writeSourceFile(newObjective, function(e) {
      return callback(e);
    });
  });
};

CreateModule.writeSpecFile = function(objective, callback) {
  return callback();
};

CreateModule.writeSourceFile = function(objective, callback) {
  return callback();
};
